### ISSUE TITLE
translation and some issues

### ISSUE THREAD

**Issue by seppini** [drasticactions/WinMasto#2]
I know the problem with the fave stars are already mentioned 
I'm using a Lumia 650 and have the same problem.

![wp_ss_20170524_0001](https://cloud.githubusercontent.com/assets/19688998/26424889/22abff44-40d3-11e7-9bec-08225c7d3dec.png)

Than I've a request. Is it possible to show other users when I start typing to mention them @username. Now it's like find something in darkness. 

Third and last, if you need a German translation let me know.

**Comment by drasticactions** [comment]
The favorite star issue was already on my list (and addressed before in another issue), but I'm going to open my own issue tracking it so more people don't mention it.

This only occurred in Release Mode (So, Store builds) and does not show up in Debug mode. At first, I thought it was an issue with FontAwesome.UWP, but now I think it's with the binding of the favorite attribute. But other symbols are not affected when I do the same thing. So not sure what's going on there.

Anyway, I've hardcoded it for now to show a star (38b780bcc931f7eceeeb40b5b8934215b453c8ca) and I'll figure out a better solution at some point.
