### ISSUE TITLE
Invisible link text

### ISSUE THREAD

**Issue by astra-midnight** [drasticactions/WinMasto#3]
The links are invisible on the desktop until you highlight them with the cursor. Also the fave star is invisible as well. This is the on the release version from the store. :)

EDIT: it appears that the text being invisible is only a problem on the light theme

**Comment by drasticactions** [comment]
Fixed in 16aef2ef80224e750000bdb5aaea0c8104fbf507

I didn't realize that the accent color would override the link color, so I had to set it for both light and dark themes. Should be fine for now.
