### ISSUE TITLE
Clicking 'show' on nsfw posts inside a thread (i.e. not in a timeline) doesn't show them

### ISSUE THREAD

**Issue by vivlim** [drasticactions/WinMasto#8]
I can keep clicking the Show button, but nothing happens. If I click the post itself it loads that individual post in a new view but ideally I should be able to view the posts inline.

It would be nice if the show button were bigger or had a toggle to always show in the settings.

**Comment by drasticactions** [comment]
Should be fixed with e0d204241b1980721a2810f56b757951715e469c. 

I also added the setting for NSFW with 0c7b8449ff4602a8e3e8504438ade3544e4c3014, since I agree that it does make sense. next time though, could you separate it into a new issue/enhancement?
